services:
    neph_tcpdf_generator:
        class: Ennva\NephPdfBundle\Services\NephTCPDF
        calls:
            - [setContainer, ['@?service_container']]
        #arguments:  [@service_container]
#    Ennva_neph_pdf.example:
#        class: Ennva\NephPdfBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
