services:
    neph_tcpdf_generator:
        class: Cineca\NephPdfBundle\Services\NephTCPDF
        arguments:  [@service_container]
        calls:
            - [generatePdf, ["html_string"]]
#    cineca_neph_pdf.example:
#        class: Cineca\NephPdfBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
